# Generated by Django 5.0.2 on 2025-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
